"""English presentation of legacy model labels and error messages."""

LABELS = {
    "Ala": "Wing",
    "Fuselaje": "Fuselage",
    "Nacelle": "Nacelle",
    "Objeto CAD": "CAD object",
    "Proyecto aeronáutico": "Aircraft project",
    "Aluminio 2024-T3": "Aluminum 2024-T3",
    "Aluminio 6061-T6": "Aluminum 6061-T6",
    "Aluminio 7075-T6": "Aluminum 7075-T6",
    "Acero estructural": "Structural steel",
    "Titanio Ti-6Al-4V": "Titanium Ti-6Al-4V",
    "Compuesto de fibra de carbono": "Carbon fiber composite",
    "Compuesto de fibra de vidrio": "Glass fiber composite",
}


def display_label(value):
    return LABELS.get(value, value)


# Model identifiers and stored project contents retain their original values.
ERROR_TEXT = {
    "El archivo no corresponde a un proyecto WingCAD.": "This file is not a WingCAD project.",
    "La versión del proyecto no es compatible.": "This project version is not supported.",
    "Falta la información del documento.": "Document information is missing.",
    "El nombre del documento no es válido.": "The document name is invalid.",
    "La lista de objetos del proyecto no es válida.": "The project object list is invalid.",
    "No se pudo reconstruir el proyecto guardado:": "Unable to rebuild the saved project:",
    "Un objeto guardado no tiene un formato válido.": "A saved object has an invalid format.",
    "Un objeto guardado no tiene nombre válido.": "A saved object has an invalid name.",
    "Los parámetros de '": "Invalid parameters for '",
    "' no son válidos.": "'.",
    "No se pudo leer el proyecto:": "Unable to read the project:",
    "El archivo no contiene un proyecto WingCAD válido.": "This file does not contain a valid WingCAD project.",
    "No se puede guardar el tipo ": "Cannot save objects of type ",
    "El tipo de componente '": "Component type '",
    "' no es compatible.": "' is not supported.",
    "placement debe ser una instancia de Placement.": "placement must be a Placement instance.",
    "El nombre del objeto no puede estar vacío.": "The object name cannot be empty.",
    "El identificador guardado no es válido.": "The saved identifier is invalid.",
    "la transformación produjo una geometría vacía.": "the transformation produced empty geometry.",
    "la geometría transformada no es válida.": "the transformed geometry is invalid.",
    "no se pudo crear la geometría.": "unable to create the geometry.",
    "la geometría local no es válida.": "the local geometry is invalid.",
    "El objeto ya pertenece al documento.": "The object already belongs to the document.",
    "No existe un objeto con ese identificador.": "No object exists with that identifier.",
    "La clave del componente no puede estar vacía.": "The component key cannot be empty.",
    "El componente '": "Component '",
    "' ya está registrado.": "' is already registered.",
    "' no está registrado.": "' is not registered.",
    "El componente registrado debe ser una clase.": "The registered component must be a class.",
    "La clase debe heredar de CADObject.": "The class must inherit from CADObject.",
    "La densidad debe ser mayor que cero.": "Density must be greater than zero.",
    "El espesor debe ser mayor que cero.": "Thickness must be greater than zero.",
    "Modo de superficie no válido. Use: simetrica, semiala_positiva o semiala_negativa.": "Invalid surface mode. Choose a full wing, positive half-wing or negative half-wing.",
    "No se pudo construir la geometría de ": "Unable to build the geometry of ",
    "parametros debe ser una instancia de WingParameters.": "parametros must be a WingParameters instance.",
    "parametros debe ser FuselageParameters.": "parametros must be a FuselageParameters instance.",
    "parametros debe ser NacelleParameters.": "parametros must be a NacelleParameters instance.",
    "La geometría que se intenta exportar está vacía.": "The geometry to export is empty.",
    "No se pudo transferir la geometría al formato STEP.": "Unable to transfer the geometry to STEP format.",
    "No se pudo escribir el archivo STEP.": "Unable to write the STEP file.",
    "El proyecto no contiene geometrías válidas para exportar.": "The project contains no valid geometry to export.",
    "No se pudo inicializar el exportador STEP.": "Unable to initialize the STEP exporter.",
    "No se pudo desactivar la estructura de ensamblaje STEP.": "Unable to disable the STEP assembly structure.",
    "El radio transversal debe ser mayor que cero.": "The transverse radius must be greater than zero.",
    "El radio vertical debe ser mayor que cero.": "The vertical radius must be greater than zero.",
    "No se pudo crear una sección elíptica del fuselaje.": "Unable to create an elliptical fuselage section.",
    "No se pudo cerrar una sección del fuselaje.": "Unable to close a fuselage section.",
    "No se pudo crear un extremo del fuselaje.": "Unable to create a fuselage end.",
    "OpenCascade no pudo construir el loft del fuselaje.": "OpenCascade could not build the fuselage loft.",
    "El fuselaje generado está vacío.": "The generated fuselage is empty.",
    "La longitud del fuselaje debe ser mayor que cero.": "Fuselage length must be greater than zero.",
    "El ancho del fuselaje debe ser mayor que cero.": "Fuselage width must be greater than zero.",
    "La altura del fuselaje debe ser mayor que cero.": "Fuselage height must be greater than zero.",
    "La proporción de nariz debe estar entre 0.05 y 0.45.": "The nose ratio must be between 0.05 and 0.45.",
    "La proporción de cola debe estar entre 0.05 y 0.60.": "The tail ratio must be between 0.05 and 0.60.",
    "La nariz y la cola ocupan demasiado fuselaje.": "The nose and tail occupy too much of the fuselage.",
    "La redondez de nariz debe estar entre 0.40 y 2.50.": "Nose roundness must be between 0.40 and 2.50.",
    "La redondez de cola debe estar entre 0.40 y 2.50.": "Tail roundness must be between 0.40 and 2.50.",
    "La sección final de cola debe estar entre 0.0 y 0.35.": "The tail-end section ratio must be between 0.0 and 0.35.",
    "El fuselaje necesita al menos 6 secciones.": "The fuselage needs at least 6 sections.",
    "El número máximo de secciones es 100.": "The maximum number of sections is 100.",
    "El identificador del material está vacío.": "The material identifier is empty.",
    "El nombre del material está vacío.": "The material name is empty.",
    "La densidad del material debe ser mayor que cero.": "Material density must be greater than zero.",
    "Material desconocido:": "Unknown material:",
    "El código NACA debe contener cuatro números.": "The NACA code must contain four digits.",
    "La cuerda debe ser mayor que cero.": "Chord length must be greater than zero.",
    "Se necesitan al menos 10 puntos.": "At least 10 points are required.",
    "El radio de una sección debe ser mayor que cero.": "The section radius must be greater than zero.",
    "OpenCascade no pudo crear una sección de la góndola.": "OpenCascade could not create a nacelle section.",
    "OpenCascade no pudo construir el loft exterior de la góndola.": "OpenCascade could not build the outer nacelle loft.",
    "El loft exterior de la góndola está vacío.": "The outer nacelle loft is empty.",
    "OpenCascade no pudo construir el conducto interior.": "OpenCascade could not build the inner duct.",
    "El conducto interior está vacío.": "The inner duct is empty.",
    "OpenCascade no pudo vaciar el interior de la góndola.": "OpenCascade could not hollow out the nacelle.",
    "La góndola generada está vacía.": "The generated nacelle is empty.",
    "OpenCascade generó una góndola geométricamente inválida.": "OpenCascade generated an invalid nacelle geometry.",
    "La longitud de la góndola debe ser mayor que cero.": "Nacelle length must be greater than zero.",
    "El diámetro de entrada debe ser mayor que cero.": "Inlet diameter must be greater than zero.",
    "El diámetro máximo debe ser mayor que cero.": "Maximum diameter must be greater than zero.",
    "El diámetro de salida debe ser mayor que cero.": "Outlet diameter must be greater than zero.",
    "El diámetro máximo no puede ser menor que el diámetro de entrada.": "Maximum diameter cannot be smaller than inlet diameter.",
    "El diámetro máximo no puede ser menor que el diámetro de salida.": "Maximum diameter cannot be smaller than outlet diameter.",
    "El espesor de pared debe ser mayor que cero.": "Wall thickness must be greater than zero.",
    "El espesor de pared es demasiado grande para los diámetros de la góndola.": "Wall thickness is too large for the nacelle diameters.",
    "La posición del diámetro máximo debe estar entre 0.15 y 0.75.": "The maximum-diameter position ratio must be between 0.15 and 0.75.",
    "La góndola necesita al menos 6 secciones.": "The nacelle needs at least 6 sections.",
    "El número máximo de secciones es 80.": "The maximum number of sections is 80.",
    "La cuerda raíz debe ser mayor que cero.": "Root chord must be greater than zero.",
    "La cuerda punta debe ser mayor que cero.": "Tip chord must be greater than zero.",
    "La semienvergadura debe ser mayor que cero.": "Semi-span must be greater than zero.",
    "La flecha debe estar entre -45° y 75°.": "Sweep must be between -45° and 75°.",
    "El diedro debe estar entre -20° y 45°.": "Dihedral must be between -20° and 45°.",
    "La torsión debe estar entre -20° y 20°.": "Twist must be between -20° and 20°.",
    "El número de puntos debe estar entre 20 y 300.": "The number of points must be between 20 and 300.",
    "El número de secciones debe estar entre 2 y 50.": "The number of sections must be between 2 and 50.",
    "El perfil raíz debe ser un código NACA de cuatro dígitos.": "The root airfoil must be a four-digit NACA code.",
    "El perfil punta debe ser un código NACA de cuatro dígitos.": "The tip airfoil must be a four-digit NACA code.",
    "El modelo de masa debe ser 'solido' o 'carcasa'.": "The mass model must be solid or shell.",
    "El espesor de la carcasa debe ser mayor que cero.": "Shell thickness must be greater than zero.",
    "La geometría no contiene una superficie válida.": "The geometry contains no valid surface.",
    "La geometría no contiene un volumen válido.": "The geometry contains no valid volume.",
    "Modo de superficie no válido.": "Invalid surface mode.",
    "No se pudo crear la curva B-Spline.": "Unable to create the B-spline curve.",
    "No se pudo crear la sección en Y=": "Unable to create the section at Y=",
    "OpenCascade no pudo construir el loft.": "OpenCascade could not build the loft.",
    "OpenCascade generó una semiala vacía.": "OpenCascade generated an empty half-wing.",
    "La semiala no es geométricamente válida.": "The half-wing geometry is invalid.",
    "No se pudo reflejar la semiala.": "Unable to mirror the half-wing.",
    "No se pudieron unir las dos semialas.": "Unable to join the two half-wings.",
    "La unión generó una geometría vacía.": "The union produced empty geometry.",
    "El ala completa no es válida.": "The full wing is invalid.",
    "No se recibió una geometría.": "No geometry was provided.",
    "No se puede transformar una geometría vacía.": "Cannot transform empty geometry.",
    "OpenCascade no pudo transformar el objeto.": "OpenCascade could not transform the object.",
    "La transformación produjo una geometría vacía.": "The transformation produced empty geometry.",
    "El placement guardado debe ser un diccionario.": "The saved placement must be a dictionary.",
    "El placement contiene campos desconocidos:": "The placement contains unknown fields:",
    "' debe ser numérico.": "' must be numeric.",
    "' debe ser un valor finito.": "' must be finite.",
}


def display_error(error):
    text = str(error)
    for original, english in ERROR_TEXT.items():
        text = text.replace(original, english)
    return text
